site_name: Manny's Docs
repo_url: https://github.com/mabadirwork/mdocs
site_url: https://mabadirwork.github.io/mdocs/
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - MPLX Infrastructure:
      - Overview: mplx/overview.md
      - Ansible: mplx/ansible.md
      - Satellite: mplx/satellite.md
  - Personal:
      - Career: personal/career.md
      - Setup: personal/setup.md
      - Investing: personal/tools.md