site_name: Manny's Docs
repo_url: https://github.com/mabadirwork/mdocs
site_url: https://mabadirwork.github.io/mdocs/
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - MPLX Infrastructure:
      - Overview: MPLX/overview.md
      - Ansible: MPLX/ansible.md
      - Satellite: MPLX/satellite.md
  - Personal:
      - Career: Personal/career.md
      - Setup: Personal/setup.md
      - Investing: Personal/tools.md